on:
  workflow_dispatch:
name: 🚀 Deploy current version
jobs:
  shoptet-addon-deploy:
    if: github.actor != 'shoptet-core-addon-repository[bot]'
    uses: shoptet/addon-repository-actions-config/.github/workflows/default.workflow.yml@main
